name: single_word_clickable_text
description: A Flutter package that provides a customizable widget for displaying text where each word is individually clickable.
  Ideal for applications that require interactive text, such as chat applications or tutorials.
  Supports customizing text style, alignment, and handling click events on each word.
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/guide.png

repository: https://github.com/bumbii/widgets/single_word_clickable_text
