name: Publish Flutter Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: widgets

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          echo "Branch name: ${{ env.BRANCH_NAME }}"
          cd widgets/${{ env.BRANCH_NAME }}
          flutter pub get

      - name: Publish package
        env:
          PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
        run: |
          cd widgets/${{ env.BRANCH_NAME }}
          flutter pub publish --dry-run
          flutter pub publish --force
