name: Publish Flutter Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: widgets

      - name: Install dependencies
        run: |
          cd widgets/single_word_clickable_text
          flutter pub get

      - name: Run tests
        run: |
          cd widgets/single_word_clickable_text
          flutter test

      - name: Publish package
        env:
          PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
        run: |
          cd widgets/single_word_clickable_text
          flutter pub publish --dry-run
          flutter pub publish --force
