name: Publish Flutter Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: widgets

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Get branch name
        id: get_branch
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          echo "Branch name: ${{ env.BRANCH_NAME }}"
          cd widgets/${{ env.BRANCH_NAME }}
          flutter pub get

      - name: Set up pub credentials
        run: |
          echo "${{ secrets.PUB_CREDENTIALS_JSON }}" > ~/.pub-cache/credentials.json

      - name: Publish package
        env:
          PUB_TOKEN: ${{ secrets.PUB_CREDENTIALS_JSON }}
        run: |
          cd widgets/${{ env.BRANCH_NAME }}
          flutter pub publish --dry-run
          flutter pub publish --force
